language: r

before_cache: Rscript -e 'remotes::install_cran("pkgdown")'

cache: packages

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - devscripts
env:
  - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
