#' Fit a mark-recapture model
#'
#' @param data A list of data generated by the function
#' \code{mrmr::clean_data()}.
#' @param ... Additional parameters to pass to \code{rstan::sampling()}
#' @return A list containing the stanfit object, extracted posterior draws, and
#' input data.
#' @examples
#' \dontrun{
#' captures <- system.file("extdata", "capture-example.csv", package = "mrmr")
#' translocations <- system.file("extdata", "translocation-example.csv",
#'                               package = "mrmr")
#' surveys <- system.file("extdata", "survey-example.csv", package = "mrmr")
#' out <- clean_data(captures, translocations, surveys)
#' fit_model(out, chains = 1, iter = 10)
#' }
#' @export
#' @import rstan
#' @importFrom Rcpp cpp_object_initializer

fit_model <- function(data, ...) {
  stanfile <- system.file("extdata", "two-state.stan", package = "mrmr")
  message("Compiling Stan model...")
  m_init <- rstan::stan_model(stanfile)
  m_fit <- rstan::sampling(m_init, data = data$stan_d, ...)
  post <- rstan::extract(m_fit)
  list(m_fit = m_fit, post = post, data = data)
}
