#' Plot a mark-recapture model's output
#'
#' @param model A model objectgenerated by \code{mrmr:fit_model()}.
#' @param what What to plot. Must be a character string of either
#' "abundance", "recruitment", or "survival".
#' @return A ggplot object.
#' @examples
#' \dontrun{
#' captures <- system.file("extdata", "capture-example.csv", package = "mrmr")
#' translocations <- system.file("extdata", "translocation-example.csv",
#'                               package = "mrmr")
#' surveys <- system.file("extdata", "survey-example.csv", package = "mrmr")
#' out <- clean_data(captures, translocations, surveys)
#' model <- fit_model(out, chains = 1, iter = 10)
#' plot_model(model, what = "abundance")
#' }
#' @export
#' @importFrom dplyr group_by summarize left_join ungroup filter distinct
#' @importFrom ggplot2 ggplot geom_line geom_ribbon xlab ylab facet_wrap theme
#' scale_color_brewer aes element_text scale_fill_brewer scale_x_date geom_point
#' @importFrom reshape2 melt
#' @importFrom rlang .data
#' @importFrom tibble as_tibble
#' @importFrom stats median quantile

plot_model <- function(model, what) {
  valid_plots <- c("abundance", "recruitment", "survival")
  stopifnot(what %in% valid_plots)
  if (what == "abundance") {
    p <- model$post$N %>%
      melt(varnames = c('iter', 'primary_period')) %>%
      as_tibble %>%
      mutate(primary_period = .data$primary_period + 1) %>%
      group_by(.data$primary_period) %>%
      summarize(lo = quantile(.data$value, .025),
                med = median(.data$value),
                hi = quantile(.data$value, .975)) %>%
      left_join(model$data$surveys) %>%
      ggplot(aes(.data$survey_date, .data$med)) +
      geom_line() +
      geom_point() +
      geom_ribbon(aes(ymin = .data$lo, ymax = .data$hi), alpha = .4) +
      xlab('Date') +
      ylab('Population size') +
      facet_wrap(~.data$year, nrow = 1, scales = 'free_x') +
      theme(axis.text.x = element_text(angle = 90))
  }

  if (what == "recruitment") {
    p <- model$post$B %>%
      melt(varnames = c('iter', 'primary_period')) %>%
      as_tibble %>%
      group_by(.data$primary_period) %>%
      summarize(lo = quantile(.data$value, .025),
                med = median(.data$value),
                hi = quantile(.data$value, .975)) %>%
      left_join(model$data$surveys) %>%
      ggplot(aes(.data$survey_date, .data$med)) +
      geom_line() +
      geom_point() +
      geom_ribbon(aes(ymin = .data$lo, ymax = .data$hi), alpha = .4) +
      xlab('Date') +
      ylab('Recruitment') +
      facet_wrap(~.data$year, nrow = 1, scales = 'free_x') +
      theme(axis.text.x = element_text(angle = 90))
  }

  if (what == "survival") {
    any_translocations <- 'data.frame' %in% class(model$data$translocations)
    if (!any_translocations) {
      stop(paste("No translocation data are present, so a cohort survival",
                 "plot cannot be generated. Using what='survival' requires",
                 "translocation data."))
    }

    primary_period_dates <- model$data$surveys %>%
      group_by(.data$primary_period) %>%
      summarize(date = min(.data$survey_date),
                year = min(.data$year)) %>%
      ungroup

    p <- model$post$s %>%
      melt(varnames = c('iter', 'i', 'primary_period')) %>%
      as_tibble %>%
      mutate(pit_tag_id = dimnames(model$data$stan_d$Y)[[1]][.data$i]) %>%
      filter(.data$pit_tag_id %in% as.character(model$data$translocations$pit_tag_id)) %>%
      left_join(distinct(model$data$translocations,
                         .data$pit_tag_id, .data$release_date)) %>%
      group_by(.data$release_date, .data$primary_period, .data$iter) %>%
      summarize(fraction_alive = mean(.data$value == 2)) %>%
      ungroup %>%
      filter(.data$primary_period > 1) %>%
      left_join(primary_period_dates) %>%
      filter(.data$date >= .data$release_date) %>%
      group_by(.data$release_date, .data$date) %>%
      summarize(lo = quantile(.data$fraction_alive, .025),
                med = median(.data$fraction_alive),
                hi = quantile(.data$fraction_alive, .975)) %>%
      ggplot(aes(.data$date, .data$med,
                 color = as.factor(.data$release_date),
                 fill = as.factor(.data$release_date))) +
      geom_ribbon(aes(ymin = .data$lo, ymax = .data$hi),
                  alpha = .5, color = NA) +
      geom_point() +
      geom_line() +
      ylab('Fraction surviving') +
      xlab('Date') +
      scale_color_brewer('Introduction date', type = 'qual') +
      scale_fill_brewer('Introduction date', type = 'qual') +
      scale_x_date(date_breaks = "1 year")
  }

  return(p)
}
